
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/blank-storybook
owner: ucsb-cs156
repo_name: blank-storybook
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-tryPRWorkflow2","number":3,"title":"Pc try pr workflow2","url":"https://github.com/ucsb-cs156/blank-storybook/pull/3"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-tryPRWorkflow","number":2,"title":"pc - cleanup versions of Github Actions steps","url":"https://github.com/ucsb-cs156/blank-storybook/pull/2"}]
